<a href="https://colab.research.google.com/github/rithanravikumar/MULTIPLE-DISEASE-PREDICTION---KIDNEY-LIVER-PARKINSONS./blob/main/PR_2_MULTIPLE_DISEASE_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv("/content/parkinsons - parkinsons.csv")
df1 = pd.read_csv("/content/kidney_disease - kidney_disease.csv")
df2 = pd.read_csv("/content/indian_liver_patient - indian_liver_patient.csv")

In [3]:
import statsmodels.api as sm

In [48]:
import pickle

In [4]:
pd.set_option("display.max_columns",None)

In [ ]:
df #parkinsons

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,0.02182,0.03130,0.02971,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,0.03134,0.04518,0.04368,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,0.02757,0.03858,0.03590,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,0.02924,0.04005,0.03772,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,0.03490,0.04825,0.04465,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,phon_R01_S50_2,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,0.405,0.02336,0.02498,0.02745,0.07008,0.02764,19.517,0,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,phon_R01_S50_3,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,0.263,0.01604,0.01657,0.01879,0.04812,0.01810,19.147,0,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,phon_R01_S50_4,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,0.256,0.01268,0.01365,0.01667,0.03804,0.10715,17.883,0,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,phon_R01_S50_5,198.764,396.961,74.904,0.00740,0.00004,0.00370,0.00390,0.01109,0.02296,0.241,0.01265,0.01321,0.01588,0.03794,0.07223,19.020,0,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,phon_R01_S50_6,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,0.190,0.01026,0.01161,0.01373,0.03078,0.04398,21.209,0,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [ ]:
df1 #kidney

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [ ]:
df2 #liver

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

# PARKINSONS

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [ ]:
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encode=OrdinalEncoder()

for i in df.select_dtypes(include=["object"]).columns:
   df[i]=encode.fit_transform(df[[i]])

In [ ]:
df

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,0.0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,0.02182,0.03130,0.02971,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,1.0,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,0.03134,0.04518,0.04368,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,2.0,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,0.02757,0.03858,0.03590,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,3.0,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,0.02924,0.04005,0.03772,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,4.0,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,0.03490,0.04825,0.04465,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,190.0,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,0.405,0.02336,0.02498,0.02745,0.07008,0.02764,19.517,0,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,191.0,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,0.263,0.01604,0.01657,0.01879,0.04812,0.01810,19.147,0,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,192.0,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,0.256,0.01268,0.01365,0.01667,0.03804,0.10715,17.883,0,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,193.0,198.764,396.961,74.904,0.00740,0.00004,0.00370,0.00390,0.01109,0.02296,0.241,0.01265,0.01321,0.01588,0.03794,0.07223,19.020,0,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,194.0,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,0.190,0.01026,0.01161,0.01373,0.03078,0.04398,21.209,0,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [ ]:
x=df.drop("status",axis=1)
y=df["status"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((97, 23), (98, 23), (97,), (98,))

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [ ]:
y_train.value_counts()

status
1    72
0    25
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

status
1    75
0    23
Name: count, dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report # Import classification_report

model = RandomForestClassifier().fit(x_train,y_train)
y_pred=model.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.07142857142857142
0.07142857142857142
0.6335470085470085
              precision    recall  f1-score   support

           0       0.88      0.85      0.86        26
           1       0.95      0.96      0.95        72

    accuracy                           0.93        98
   macro avg       0.91      0.90      0.91        98
weighted avg       0.93      0.93      0.93        98

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report # Import classification_report

model2 = XGBClassifier().fit(x_train,y_train)
y_pred=model2.predict(x_test)
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.061224489795918366
0.061224489795918366
0.6858974358974359
              precision    recall  f1-score   support

           0       0.88      0.88      0.88        26
           1       0.96      0.96      0.96        72

    accuracy                           0.94        98
   macro avg       0.92      0.92      0.92        98
weighted avg       0.94      0.94      0.94        98

In [ ]:
import pickle
with open("parkinsons.pkl","wb") as f:
       pickle.dump(model2,f)

# KIDNEY

In [22]:
df1 #kidney

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,49.0,0.5,150.0,4.9,15.7,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,31.0,1.2,141.0,3.5,16.5,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,26.0,0.6,137.0,4.4,15.8,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,50.0,1.0,135.0,4.9,14.2,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,18.0,1.1,141.0,3.5,15.8,53,6800,6.1,no,no,no,good,no,no,notckd

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [24]:
df1.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [25]:
df1["pcv"].unique()

array(['44', '38', '31', '32', '35', '39', '36', '33', '29', '28', nan,
       '16', '24', '37', '30', '34', '40', '45', '27', '48', '?', '52',
       '14', '22', '18', '42', '17', '46', '23', '19', '25', '41', '26',
       '15', '21', '43', '20', '47', '9', '49', '50', '53', '51', '54'],
      dtype=object)

In [27]:
df1['pcv'] = df1['pcv'].replace('?', np.nan)
df1['wc'] = df1['wc'].replace('?', np.nan)
df1['rc'] = df1['rc'].replace('?', np.nan)

In [29]:
df1 = df1.ffill().bfill()

In [30]:
df1.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [32]:
from sklearn.preprocessing import OrdinalEncoder

encode=OrdinalEncoder()

In [33]:
for i in df1.select_dtypes(include=["object"]).columns:
   df1[i]=encode.fit_transform(df1[[i]])

In [34]:
df1

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,1.0,1.0,0.0,0.0,121.0,36.0,1.2,111.0,2.5,15.4,30.0,69.0,30.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1,7.0,50.0,1.020,4.0,0.0,1.0,1.0,0.0,0.0,121.0,18.0,0.8,111.0,2.5,11.3,24.0,53.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,62.0,80.0,1.010,2.0,3.0,1.0,1.0,0.0,0.0,423.0,53.0,1.8,111.0,2.5,9.6,17.0,67.0,30.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,3,48.0,70.0,1.005,4.0,0.0,1.0,0.0,1.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,18.0,59.0,17.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0
4,4,51.0,80.0,1.010,2.0,0.0,1.0,1.0,0.0,0.0,106.0,26.0,1.4,111.0,2.5,11.6,21.0,65.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1.0,1.0,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7,33.0,59.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
396,396,42.0,70.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5,40.0,69.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
397,397,12.0,80.0,1.020,0.0,0.0,1.0,1.0,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8,35.0,58.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
398,398,17.0,60.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2,37.0,64.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
399,399,58.0,80.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8,39.0,60.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [35]:
x3=df1.drop("classification",axis=1)
y3=df1["classification"]

In [41]:
from sklearn.model_selection import train_test_split
x3_train,x3_test,y3_train,y3_test=train_test_split(x3,y3,test_size=0.3)
x3_train.shape,x3_test.shape,y3_train.shape,y3_test.shape

((280, 25), (120, 25), (280,), (120,))

In [42]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [43]:
y3_train.value_counts()

classification
0.0    180
1.0    100
Name: count, dtype: int64

In [44]:
y3_test.value_counts()

classification
0.0    70
1.0    50
Name: count, dtype: int64

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report # Import classification_report

model1K = RandomForestClassifier().fit(x3_train,y3_train)
y3_pred=model1K.predict(x3_test)
print(mean_squared_error(y3_test,y3_pred))
print(mean_absolute_error(y3_test,y3_pred))
print(r2_score(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))

0.0
0.0
1.0
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        70
         1.0       1.00      1.00      1.00        50

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [46]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report # Import classification_report

model2K = RandomForestClassifier().fit(x3_train,y3_train)
y3_pred=model2K.predict(x3_test)
print(mean_squared_error(y3_test,y3_pred))
print(mean_absolute_error(y3_test,y3_pred))
print(r2_score(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))

0.0
0.0
1.0
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        70
         1.0       1.00      1.00      1.00        50

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report # Import classification_report

model3K = DecisionTreeClassifier().fit(x3_train,y3_train)
y3_pred=model3K.predict(x3_test)
print(mean_squared_error(y3_test,y3_pred))
print(mean_absolute_error(y3_test,y3_pred))
print(r2_score(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))

0.008333333333333333
0.008333333333333333
0.9657142857142857
              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99        70
         1.0       0.98      1.00      0.99        50

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120

In [49]:
with open("kidney.pkl","wb") as f:
       pickle.dump(model1K,f)

# **LIVER**

In [5]:
df2 #liver

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    object
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  579 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB

In [7]:
df2.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [8]:
df2 = df2.rename(columns={'Dataset': 'Disease_status'})

In [9]:
df2["Disease_status"]=df2["Disease_status"]-1

In [11]:
from sklearn.preprocessing import OrdinalEncoder

encode=OrdinalEncoder()

In [12]:
for i in df2.select_dtypes(include=["object"]).columns:
   df2[i]=encode.fit_transform(df2[[i]])

In [13]:
df2

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Disease_status
0,65,0.0,0.7,0.1,187,16,18,6.8,3.3,0.90,0
1,62,1.0,10.9,5.5,699,64,100,7.5,3.2,0.74,0
2,62,1.0,7.3,4.1,490,60,68,7.0,3.3,0.89,0
3,58,1.0,1.0,0.4,182,14,20,6.8,3.4,1.00,0
4,72,1.0,3.9,2.0,195,27,59,7.3,2.4,0.40,0
...,...,...,...,...,...,...,...,...,...,...,...
578,60,1.0,0.5,0.1,500,20,34,5.9,1.6,0.37,1
579,40,1.0,0.6,0.1,98,35,31,6.0,3.2,1.10,0
580,52,1.0,0.8,0.2,245,48,49,6.4,3.2,1.00,0
581,31,1.0,1.3,0.5,184,29,32,6.8,3.4,1.00,0
582,38,1.0,1.0,0.3,216,21,24,7.3,4.4,1.50,1

In [14]:
x2=df2.drop("Disease_status",axis=1)
y2=df2["Disease_status"]

In [15]:
from sklearn.model_selection import train_test_split
x2_train,x2_test,y2_train,y2_test=train_test_split(x2,y2,test_size=0.5)
x2_train.shape,x2_test.shape,y2_train.shape,y2_test.shape

((291, 10), (292, 10), (291,), (292,))

In [16]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [17]:
y2_train.value_counts()

Disease_status
0    213
1     78
Name: count, dtype: int64

In [18]:
y2_test.value_counts()

Disease_status
0    203
1     89
Name: count, dtype: int64

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report # Import classification_report

model1L = RandomForestClassifier().fit(x2_train,y2_train)
y2_pred=model1L.predict(x2_test)
print(mean_squared_error(y2_test,y2_pred))
print(mean_absolute_error(y2_test,y2_pred))
print(r2_score(y2_test,y2_pred))
print(classification_report(y2_test,y2_pred))

0.2842465753424658
0.2842465753424658
-0.34145126473681264
              precision    recall  f1-score   support

           0       0.75      0.90      0.81       203
           1       0.56      0.30      0.39        89

    accuracy                           0.72       292
   macro avg       0.65      0.60      0.60       292
weighted avg       0.69      0.72      0.69       292

In [20]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report # Import classification_report

model2L = RandomForestClassifier().fit(x2_train,y2_train)
y2_pred=model2L.predict(x2_test)
print(mean_squared_error(y2_test,y2_pred))
print(mean_absolute_error(y2_test,y2_pred))
print(r2_score(y2_test,y2_pred))
print(classification_report(y2_test,y2_pred))

0.2910958904109589
0.2910958904109589
-0.3737753915979407
              precision    recall  f1-score   support

           0       0.74      0.89      0.81       203
           1       0.54      0.29      0.38        89

    accuracy                           0.71       292
   macro avg       0.64      0.59      0.59       292
weighted avg       0.68      0.71      0.68       292

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report # Import classification_report

model3L = DecisionTreeClassifier().fit(x2_train,y2_train)
y2_pred=model3L.predict(x2_test)
print(mean_squared_error(y2_test,y2_pred))
print(mean_absolute_error(y2_test,y2_pred))
print(r2_score(y2_test,y2_pred))
print(classification_report(y2_test,y2_pred))

0.3253424657534247
0.3253424657534247
-0.5353960259035808
              precision    recall  f1-score   support

           0       0.74      0.82      0.78       203
           1       0.46      0.35      0.39        89

    accuracy                           0.67       292
   macro avg       0.60      0.58      0.59       292
weighted avg       0.65      0.67      0.66       292

In [50]:
with open("liver.pkl","wb") as f:
       pickle.dump(model1L,f)